"""Persisted evidence schema versions and compatibility ranges."""

COHORT_SCHEMA_VERSION = 2
RUN_RECORD_SCHEMA_VERSION = 6
SUPPORTED_RUN_RECORD_SCHEMA_VERSIONS = frozenset({5, RUN_RECORD_SCHEMA_VERSION})
REPORT_SCHEMA_VERSION = 8
METRIC_EXPORT_SCHEMA_VERSION = 6
